-- ============================================================================
-- 1. SECURITY & ACCESS CONTROL MODULE
-- ============================================================================

CREATE TABLE roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    require_password_change BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE user_roles (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Seed foundational system roles
INSERT INTO roles (name) VALUES
('ROLE_ADMIN'),
('ROLE_COACH'),
('ROLE_PARENT'),
('ROLE_PLAYER');


-- ============================================================================
-- 2. MANAGEMENT CATEGORIES (Tiers / Age Groups)
-- ============================================================================

CREATE TABLE categories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(255)
);

-- Seed baseline configuration
INSERT INTO categories (name, description) VALUES
('GENERAL', 'Default category for unassigned team fixtures');


-- ============================================================================
-- 3. CORE USER SATELLITE PROFILES
-- ============================================================================

CREATE TABLE parents (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(20),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    address TEXT NOT NULL
);

CREATE TABLE coaches (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    specialization VARCHAR(100),
    license_level VARCHAR(50),
    employee_id VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE players (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    player_id VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20),
    date_of_birth DATE NOT NULL,
    address TEXT,
    state_of_origin VARCHAR(50),
    country VARCHAR(50),
    healthy BOOLEAN NOT NULL DEFAULT TRUE,
    health_concerns TEXT,
    passport_url VARCHAR(500),
    parent_id BIGINT REFERENCES parents(user_id) ON DELETE SET NULL
);

CREATE TABLE admins (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    employee_id VARCHAR(30) UNIQUE NOT NULL
);


-- ============================================================================
-- 4. CALENDAR PLANNER & TIMELINE MODULE
-- ============================================================================

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    activities_description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    name VARCHAR(30) NOT NULL,
    syllabus_url VARCHAR(500),
    matches_description TEXT,
    assessment_description TEXT,
    results_summary TEXT,
    opening_account_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    closing_account_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT unique_term_per_session UNIQUE (session_id, name)
);


-- ============================================================================
-- 5. ATHLETIC METRICS & PERFORMANCE
-- ============================================================================

CREATE TABLE player_profiles (
    player_id BIGINT PRIMARY KEY REFERENCES players(user_id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    height_cm DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    weight_kg DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    dominant_foot VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    position VARCHAR(30) NOT NULL DEFAULT 'UNASSIGNED',
    preferred_jersey_number INT,
    biography TEXT
);

CREATE TABLE attendance_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_date DATE NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE player_attendance_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES attendance_events(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES players(user_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    remarks VARCHAR(255),
    CONSTRAINT unique_player_per_event UNIQUE (event_id, player_id)
);

CREATE INDEX idx_attendance_player ON player_attendance_lines(player_id);
CREATE INDEX idx_attendance_event ON player_attendance_lines(event_id);


-- ============================================================================
-- 6. ACCOUNTS & FINANCIALS MODULE
-- ============================================================================

CREATE TABLE accounts (
    player_id BIGINT PRIMARY KEY REFERENCES players(user_id) ON DELETE CASCADE,
    account_id VARCHAR(100) UNIQUE NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    current_pending NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    outstandings NUMERIC(12, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_player_id BIGINT NOT NULL REFERENCES accounts(player_id) ON DELETE CASCADE,
    term_id BIGINT REFERENCES terms(id) ON DELETE SET NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    tuition_fee NUMERIC(12, 2) NOT NULL,
    kit_fee NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    other_fees NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_player_id BIGINT NOT NULL REFERENCES accounts(player_id) ON DELETE CASCADE,
    amount_paid NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    reference_number VARCHAR(100),
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================================
-- 7. MATCH MANAGEMENT MODULE
-- ============================================================================

CREATE TABLE matches (
    id BIGSERIAL PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    opponent_name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    venue VARCHAR(255) NOT NULL,
    started BOOLEAN NOT NULL DEFAULT FALSE,
    is_live BOOLEAN NOT NULL DEFAULT FALSE,
    ended BOOLEAN NOT NULL DEFAULT FALSE,
    is_home_match BOOLEAN NOT NULL,
    is_away_match BOOLEAN NOT NULL,
    home_team_score INT NOT NULL DEFAULT 0,
    away_team_score INT NOT NULL DEFAULT 0,
    match_type VARCHAR(50) NOT NULL,
    half_duration INT NOT NULL DEFAULT 45,
    is_extra_time BOOLEAN NOT NULL DEFAULT FALSE,
    is_penalty_shootout BOOLEAN NOT NULL DEFAULT FALSE,
    home_team_penalty_score INT DEFAULT 0,
    away_team_penalty_score INT DEFAULT 0
);

CREATE TABLE match_events (
    id BIGSERIAL PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    match_time VARCHAR(10) NOT NULL,
    event_type VARCHAR(50) NOT NULL
);

-- Polymorphic Sub-event tables
CREATE TABLE events_generic (
    id BIGINT PRIMARY KEY REFERENCES match_events(id) ON DELETE CASCADE,
    state_name VARCHAR(100)
);

CREATE TABLE events_freekick (
    id BIGINT PRIMARY KEY REFERENCES match_events(id) ON DELETE CASCADE,
    dangerous_position BOOLEAN NOT NULL DEFAULT FALSE,
    taker_user_id BIGINT REFERENCES players(user_id) ON DELETE SET NULL  -- 👈 Renamed here
);

CREATE TABLE goals (
    id BIGSERIAL PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    match_time VARCHAR(10) NOT NULL,
    scorer_id BIGINT NOT NULL REFERENCES players(user_id) ON DELETE CASCADE,
    goal_count INT NOT NULL,
    is_freekick BOOLEAN NOT NULL,
    is_penalty BOOLEAN NOT NULL,
    is_own_goal BOOLEAN NOT NULL
);

CREATE TABLE substitutions (
    id BIGSERIAL PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    match_time VARCHAR(10) NOT NULL,
    player_in_id BIGINT NOT NULL REFERENCES players(user_id) ON DELETE CASCADE,
    player_out_id BIGINT NOT NULL REFERENCES players(user_id) ON DELETE CASCADE
);

-- Element Collections & Junction tables
CREATE TABLE match_photos (
    match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    photo_url VARCHAR(500) NOT NULL
);

CREATE TABLE match_videos (
    match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    video_url VARCHAR(500) NOT NULL
);

CREATE TABLE match_starting_lineup (
    match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES players(user_id) ON DELETE CASCADE,
    PRIMARY KEY (match_id, player_id)
);